// <auto-generated />
namespace UnitTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class finialisev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finialisev1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508240320119_finialisev1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
